"""empty message

Revision ID: 52395ced0e22
Revises: e5fa18bb1d7b
Create Date: 2020-01-08 14:18:29.644450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52395ced0e22'
down_revision = 'e5fa18bb1d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
