"""empty message

Revision ID: 536f415c7eba
Revises: 64108eb7328b
Create Date: 2020-01-06 23:00:25.686921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536f415c7eba'
down_revision = '64108eb7328b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_text')
    # ### end Alembic commands ###
