"""empty message

Revision ID: e5fa18bb1d7b
Revises: 7cb97fa13743
Create Date: 2020-01-07 22:55:14.506866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fa18bb1d7b'
down_revision = '7cb97fa13743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.drop_index('ix_comment_timestamp', table_name='comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comment_timestamp', 'comments', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    # ### end Alembic commands ###
