"""empty message

Revision ID: f15a6951e1e3
Revises: 20528b50b0ef
Create Date: 2020-01-03 11:06:41.490172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15a6951e1e3'
down_revision = '20528b50b0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('icon', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'icon')
    # ### end Alembic commands ###
